main: com.cavetale.menu.MenuPlugin

name: Menu
version: 0.1
description: Chest Menus
api-version: 1.13

author: StarTux
website: https://github.com/StarTux/Menu

depend: [Core]
softdepend: []

commands:

  menu:
    aliases: [m]
    description: Menu Command
    permission: menu.menu
    usage: |-
      /menu

  menuadmin:
    aliases: [madmin]
    description: Menu Admin Command
    permission: menu.admin
    usage: |-
      /menuadmin

permissions:

  menu.menu:
    description: Use /menu
    default: op

  menu.admin:
    description: Use /menuadmin
    default: op
